# Generated by Django 4.2.7 on 2023-11-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0002_jewelry_id_alter_jewelry_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='ID',
        ),
        migrations.AddField(
            model_name='jewelry',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
