# Generated by Django 4.2.7 on 2023-11-22 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0004_jewelry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='id',
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, message='ID should be a positive integer.')]),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='jewelry_type',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(rings|earrings|bracelets)$', message='Invalid type of jewelry.')]),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='material',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(gold|silver|platinum)$', message='Invalid material option.')]),
        ),
    ]
