# Generated by Django 4.2.7 on 2023-11-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0005_remove_jewelry_id_alter_jewelry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
