# Generated by Django 4.2.7 on 2023-11-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0006_alter_jewelry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='date_of_creation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='jewelry_type',
            field=models.CharField(choices=[('rings', 'Rings'), ('earrings', 'Earrings'), ('bracelets', 'Bracelets')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='material',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
