# Generated by Django 4.2.7 on 2023-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0008_alter_jewelry_code_alter_jewelry_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='date_of_creation',
            field=models.DateField(),
        ),
    ]
