# Generated by Django 4.2.7 on 2023-11-23 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0012_alter_jewelry_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1, message='ID should be a positive integer.')]),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.RegexValidator('^\\d+\\.\\d[0-9]?$', message='Please enter a valid price.')]),
        ),
    ]
