# Generated by Django 4.2.7 on 2023-11-25 17:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0013_alter_jewelry_id_alter_jewelry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='date_of_creation',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 11, 25), message="The date can't be in the future.")]),
        ),
        migrations.DeleteModel(
            name='JewelryHistory',
        ),
    ]
